import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { Wrapper, Status } from "@googlemaps/react-wrapper";
import { useEffect, useRef, useState } from 'react';
import MapsGoogle from '../../components/Maps';
// import Script from "next/script";



const Home: NextPage = () => {

  const render = (status: Status) => {
    return <h1>{status}</h1>;
  };


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          GPS
        </h1>

        <Wrapper 
          apiKey={"AIzaSyAKmAuVwbZG4H9-msa3CVvbNVm6Jx4Bltg"}
          render={render}
          >
          <MapsGoogle 
            center={center} 
            zoom={zoom}
          />
        </Wrapper>

      </main>

      <footer className={styles.footer}>
        <a
          href="./.."
        >
          Home Page{' <-- '}
        </a>
      </footer>
    </div>
  )
}

export default Home
