import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import styles from '../../styles/Home.module.css'

const Home: NextPage = () => {
    


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Camera
        </h1>
        <iframe 
          src="https://smartcampus.maua.br" 
          width={"100%"} 
          height={720} 
          frameBorder={0} 
          allow='accelerometer'
          >
        </iframe>
      </main>

      <footer className={styles.footer}>
        <a
          href="./.."
        >
          Home Page{' <-- '}
        </a>
      </footer>
    </div>
  )
}

export default Home
