import type { NextPage } from 'next'
import Head from 'next/head'

import styles from '../../styles/Home.module.css'
import Webcam from "react-webcam";


const Camera: NextPage = () => {

  const videoConstraints = {
    width: 1280,
    height: 720,
    facingMode: "user"
  };
    
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Camera
        </h1>
        <Webcam />

      </main>

      <footer className={styles.footer}>
        <a
          href="./.."
        >
          Home Page{' <-- '}
        </a>
      </footer>
    </div>
  )
}

export default Camera




// import "./styles.css";
// import { useState } from "react";
// import WebcamVideo from "./WebcamVideo";

// export default function App() {
//   const [toggleTab, setToggleTab] = useState(true);
//   return (
//     <div className="w-5/6 mx-auto">
//       {toggleTab ? (
//         <div className="h-44 w-full">
//           <WebcamVideo />
//         </div>
//       ) : (
//         <div>
//           <div className="font-bold mb-10 text-lg">Not webcam</div>
//           <div className="h-96">None</div>
//         </div>
//       )}
//       <button onClick={() => setToggleTab(!toggleTab)}>Toggle webcam</button>
//     </div>
//   );
// }
